In [1]:
import numpy as np


In [2]:
!pip install numpy


zsh:1: /usr/local/bin/pip: bad interpreter: /usr/local/opt/python@3.10/bin/python3.10: no such file or directory

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip


In [3]:
arr =np.array([1,3,4])

In [4]:
arr

array([1, 3, 4])

In [5]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [13]:
np.linspace(1,100,5) #(evenly spaced)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [17]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [18]:
myarr.shape #(4, 3) → 4 rows, 3 columns

(4, 3)

In [19]:
myarr.size #total no. of elements

12

In [20]:
myarr.ndim #dimension→ 2D array

2

In [21]:
myarr.dtype # int64 (or int32 on Windows)

dtype('int64')

In [22]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]], dtype='float32')

In [23]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [28]:
n = myarr.astype('float64')# Convert float to int

In [29]:
n.dtype

dtype('float64')

In [30]:
myarr.dtype

dtype('float32')

In [31]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]]) 

In [32]:
myarr.shape

(4, 3)

In [33]:
reshaped = myarr.reshape((3,4))

In [34]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [35]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [36]:
myarr.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11, 12, 13]])

In [37]:
myarr.reshape((2,5))

ValueError: cannot reshape array of size 12 into shape (2,5)

In [38]:
flattened = myarr.flatten()

In [39]:
flattened # Convert 2D → 1D one-dimensional array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])