In [1]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
flat =arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [5]:
flat[0]

1

In [6]:
flat[3]

4

In [8]:
flat[3:7]

array([4, 5, 6, 7])

In [9]:
flat[:5] #same as flat[0:5]

array([1, 2, 3, 4, 5])

In [10]:
flat[3:] #same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [12]:
flat[::2]

array([ 1,  3,  5,  7,  9, 12])

In [19]:
b = flat[3:7]

In [14]:
b

array([4, 5, 6, 7])

In [15]:
b[0] = 44444

In [16]:
b

array([44444,     5,     6,     7])

In [17]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          11,    12,    13])

In [18]:
#Slicing returns a view, not a copy! Changes affect the original array.**This might seem counterintuitive since Python lists
#create copies when sliced.But in NumPy, slicing returns a view of the original array. Both the sliced array and the original
#array share the same data inmemory, so changes in the slice affect the original array.

In [20]:
b = flat[3:7].copy() #this is not a slice because we are using copy method to get the copy.

In [21]:
b

array([44444,     5,     6,     7])

In [22]:
b[0]= 23

In [23]:
b

array([23,  5,  6,  7])

In [24]:
flat

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          11,    12,    13])

In [25]:
arr = np.array([1,222,3,4,5,6,45,2,3])

In [26]:
arr[[1,4,6]]  # fancy indexing(select mutliple elements)

array([222,   5,  45])

In [27]:
arr[arr>3] #condition is given (boolean masking)

array([222,   4,   5,   6,  45])

In [28]:
#exercise


In [31]:
#Create a 3×3 array filled with random numbers and print its shape.
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])


In [33]:
arr.shape

(3, 3)

In [37]:
#Convert an array of floats [1.1, 2.2, 3.3] into integers.
myarr = np.array([1.1,2.2,3.3])
arr_int = myarr.astype(int) 

In [39]:
arr_int

array([1, 2, 3])

In [41]:
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arr =np.array([1,2,3,4,5,6])
arr[[1,3,5]]

array([2, 4, 6])

In [44]:
#Reshape a 1D array of size 9 into a 3×3 matrix.
my_arr =np.array([ 1,  2,  3,  4,  5,  6,  7,  8, 9])
my_arr.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
#Use boolean masking to filter numbers greater than 50 in an array.
arr =  np.array([1,44,55,33,89,66,65,34,55,222,4444,66,66])
arr[arr>50]

array([  55,   89,   66,   65,   55,  222, 4444,   66,   66])