In [1]:
import numpy as np
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])


In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr[0] 

array([1, 2, 3])

In [4]:
arr[1]

array([4, 5, 6])

In [5]:
np.sum(arr,axis=0)#Axis 0 (rows)→ Operations move down the columns.---- Column-wise sum

array([12, 15, 18])

In [6]:
np.sum(arr,axis=1) #Axis 1 (columns) → Operations move across the rows.--- Row-wise sum

array([ 6, 15, 24])

In [7]:
arr[0][1]

2

In [9]:
arr[0,1]# 0'th row 1'st column

2

In [10]:
arr[0:2,1:3]# Extracts first 2 rows and last 2 columns

array([[2, 3],
       [5, 6]])

In [16]:
arr3D[:,0,:]=0

In [26]:
arr3D = np.array([
    [[ 1,  2,  3],   # Depth 0, Row 0
     [ 4,  5,  6]],  # Depth 0, Row 1

    [[ 7,  8,  9],   # Depth 1, Row 0
     [10, 11, 12]]   # Depth 1, Row 1
])
print(arr3D.shape)   

(2, 2, 3)


In [27]:
print(arr3D[0, 1, 2])

6


In [28]:
print(arr3D[:,0,:])

[[1 2 3]
 [7 8 9]]


In [17]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])

In [29]:
#Axis 0 = rows (vertical movement), Axis 1 = columns (horizontal movement)
#Indexing works as arr[row, column] for 2D arrays and arr[depth, row, column] for 3D arrays

In [30]:
first_col = arr[:, 0]# Get all rows of the first column
print(first_col) 

[1 4 7]


In [31]:
# Get the first row from each "depth" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


In [32]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]]
